[versions]
# Common
smartbrainlib = "1.16.4"
minecraft-range = "[1.21.3,)"
minecraft = "1.21.3"
parchment-minecraft = "1.21"
parchment = "2024.07.28"
neoform = "1.21.3-20241023.131943"
jopt-simple = "5.0.4"
java = "21"

# Fabric
fabric = "0.16.7"
fabric-range = "0.16"
fabric-api = "0.106.1+1.21.3"
fabric-api-range = "0.106.0+1.21.3"

# Neoforge
neoforge-loader-range = "[4,)"
neoforge-range = "[21.3.0-beta,)"
neoforge = "21.3.0-beta"

# Dependencies
mixin = "0.8.7"
mixinextras = "0.3.5"
mixinextras-range = "[0.3.5,)"

# Plugins
plugin-moddevgradle = "2.0.42-beta"
plugin-minotaur = "2.8.7"
plugin-curseforge-gradle = "1.1.25"
plugin-idea-ext = "1.1.8"
plugin-mixin = "0.7.+"
plugin-loom = "1.8-SNAPSHOT"

[libraries]
# Mixin
mixin = { group = "org.spongepowered", name = "mixin", version.ref = "mixin" }
mixinextras-common = { group = "io.github.llamalad7", name = "mixinextras-common", version.ref = "mixinextras" }

# Platform
neoforge = { group = "net.neoforged", name = "neoforge", version.ref = "neoforge" }
fabric = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }

[plugins]
# Publishing
minotaur = { id = "com.modrinth.minotaur", version.ref = "plugin-minotaur" }
curseforgegradle = { id = "net.darkhax.curseforgegradle", version.ref = "plugin-curseforge-gradle" }

# Platform
moddevgradle = { id = "net.neoforged.moddev", version.ref = "plugin-moddevgradle" }
loom = { id = "fabric-loom", version.ref = "plugin-loom" }

# Misc
ideaext = { id = "org.jetbrains.gradle.plugin.idea-ext", version.ref = "plugin-idea-ext" }
mixin = { id = "org.spongepowered.mixin", version.ref = "plugin-mixin" }